<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 4.1.3 (Python 3.8.10 on linux)" generated="20220623 11:51:18.328" rpa="false" schemaversion="2">
<suite id="s1" name="TC1" source="/home/indranee/Mobile application/Test_suite/TC1.robot">
<test id="s1-t1" name="TC1">
<kw name="Swipe Left" library="Mobile">
<doc>Swipe the UI object with *selectors* from center to left.</doc>
<status status="PASS" starttime="20220623 11:51:18.855" endtime="20220623 11:51:33.027"/>
</kw>
<status status="PASS" starttime="20220623 11:51:18.854" endtime="20220623 11:51:33.028"/>
</test>
<doc>Test_001: General Script for verifying functionality</doc>
<status status="PASS" starttime="20220623 11:51:18.329" endtime="20220623 11:51:33.029"/>
</suite>
<statistics>
<total>
<stat pass="1" fail="0" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="1" fail="0" skip="0" id="s1" name="TC1">TC1</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20220623 11:51:18.340" level="ERROR">Error in file '/home/indranee/Mobile application/Test_suite/TC1.robot' on line 2: Test library '/home/indranee/Mobile application/Test_suite/Lib/Android/localuiautomatorlibrary/Mobile.py' does not exist.</msg>
</errors>
</robot>
